# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/Downloads/ZYBO-master/projects/DigitalAudio/I2S_Audioplayer/hardware/I2S_AudioPlayer.srcs/sources_1/bd/System/ip/System_processing_system7_0_1/System_processing_system7_0_1.xci
# IP: The module: 'System_processing_system7_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Downloads/ZYBO-master/projects/DigitalAudio/I2S_Audioplayer/hardware/I2S_AudioPlayer.srcs/sources_1/bd/System/ip/System_processing_system7_0_1/System_processing_system7_0_1.xdc
# XDC: The top module name and the constraint reference have the same name: 'System_processing_system7_0_1'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: D:/Downloads/ZYBO-master/projects/DigitalAudio/I2S_Audioplayer/hardware/I2S_AudioPlayer.srcs/sources_1/bd/System/ip/System_processing_system7_0_1/System_processing_system7_0_1.xci
# IP: The module: 'System_processing_system7_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Downloads/ZYBO-master/projects/DigitalAudio/I2S_Audioplayer/hardware/I2S_AudioPlayer.srcs/sources_1/bd/System/ip/System_processing_system7_0_1/System_processing_system7_0_1.xdc
# XDC: The top module name and the constraint reference have the same name: 'System_processing_system7_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
